export const ORDER_CREATE = {
    _REQUEST: 'ORDER_CREATE_REQUEST',
    _SUCCESS: 'ORDER_CREATE_SUCCESS',
    _FAIL: 'ORDER_CREATE_FAIL',
}

export const ORDER_DETAILS = {
    _REQUEST: 'ORDER_DETAILS_REQUEST',
    _SUCCESS: 'ORDER_DETAILS_SUCCESS',
    _FAIL: 'ORDER_DETAILS_FAIL',
}

export const ORDER_PAY = {
    _REQUEST: 'ORDER_PAY_REQUEST',
    _SUCCESS: 'ORDER_PAY_SUCCESS',
    _FAIL: 'ORDER_PAY_FAIL',
    _RESET: 'ORDER_PAY_RESET',
}

export const ORDER_LIST_MY = {
    _REQUEST: 'ORDER_LIST_MY_REQUEST',
    _SUCCESS: 'ORDER_LIST_MY_SUCCESS',
    _FAIL: 'ORDER_LIST_MY_FAIL',
    _RESET: 'ORDER_LIST_MY_RESET',
}

export const ORDER_LIST = {
    _REQUEST: 'ORDER_LIST_REQUEST',
    _SUCCESS: 'ORDER_LIST_SUCCESS',
    _FAIL: 'ORDER_LIST_FAIL',
}

export const ORDER_DELIVER = {
    _REQUEST: 'ORDER_DELIVER_REQUEST',
    _SUCCESS: 'ORDER_DELIVER_SUCCESS',
    _FAIL: 'ORDER_DELIVER_FAIL',
    _RESET: 'ORDER_DELIVER_RESET',
}
