export const ORDER_CREATE = {
    _REQUEST: 'ORDER_CREATE_REQUEST',
    _SUCCESS: 'ORDER_CREATE_SUCCESS',
    _FAIL: 'ORDER_CREATE_FAIL',
}

export const ORDER_DETAILS = {
    _REQUEST: 'ORDER_DETAILS_REQUEST',
    _SUCCESS: 'ORDER_DETAILS_SUCCESS',
    _FAIL: 'ORDER_DETAILS_FAIL',
}
