export const PRODUCT_LIST = {
    _REQUEST: 'PRODUCT_LIST_REQUEST',
    _SUCCESS: 'PRODUCT_LIST_SUCCESS',
    _FAIL: 'PRODUCT_LIST_FAIL',
}

export const PRODUCT_DETAILS = {
    _REQUEST: 'PRODUCT_DETAILS_REQUEST',
    _SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
    _FAIL: 'PRODUCT_DETAILS_FAIL',
}

export const PRODUCT_DELETE = {
    _REQUEST: 'PRODUCT_DELETE_REQUEST',
    _SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    _FAIL: 'PRODUCT_DELETE_FAIL',
}

export const PRODUCT_CREATE = {
    _REQUEST: 'PRODUCT_CREATE_REQUEST',
    _SUCCESS: 'PRODUCT_CREATE_SUCCESS',
    _FAIL: 'PRODUCT_CREATE_FAIL',
    _RESET: 'PRODUCT_CREATE_RESET',
}

export const PRODUCT_UPDATE = {
    _REQUEST: 'PRODUCT_UPDATE_REQUEST',
    _SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
    _FAIL: 'PRODUCT_UPDATE_FAIL',
    _RESET: 'PRODUCT_UPDATE_RESET',
}

export const PRODUCT_CREATE_REVIEW = {
    _REQUEST: 'PRODUCT_CREATE_REVIEW_REQUEST',
    _SUCCESS: 'PRODUCT_CREATE_REVIEW_SUCCESS',
    _FAIL: 'PRODUCT_CREATE_REVIEW_FAIL',
    _RESET: 'PRODUCT_CREATE_REVIEW_RESET',
}
