export const PRODUCT_LIST = {
    _REQUEST: 'PRODUCT_LIST_REQUEST',
    _SUCCESS: 'PRODUCT_LIST_SUCCESS',
    _FAIL: 'PRODUCT_LIST_FAIL',
}

export const PRODUCT_DETAILS = {
    _REQUEST: 'PRODUCT_DETAILS_REQUEST',
    _SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
    _FAIL: 'PRODUCT_DETAILS_FAIL',
}
