export const USER_LOGIN = {
    _REQUEST: 'USER_LOGIN_REQUEST',
    _SUCCESS: 'USER_LOGIN_SUCCESS',
    _FAIL: 'USER_LOGIN_FAIL',
}

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER = {
    _REQUEST: 'USER_REGISTER_REQUEST',
    _SUCCESS: 'USER_REGISTER_SUCCESS',
    _FAIL: 'USER_REGISTER_FAIL',
}

export const USER_DETAILS = {
    _REQUEST: 'USER_DETAILS_REQUEST',
    _SUCCESS: 'USER_DETAILS_SUCCESS',
    _FAIL: 'USER_DETAILS_FAIL',
    _RESET: 'USER_DETAILS_RESET',
}

export const USER_UPDATE_PROFILE = {
    _REQUEST: 'USER_UPDATE_REQUEST',
    _SUCCESS: 'USER_UPDATE_SUCCESS',
    _FAIL: 'USER_UPDATE_FAIL',
    _RESET: 'USER_UPDATE_RESET',
}
